import Head from 'next/head'
import Layout from '@/components/Layout'
import FirstSection from '@/components/FirstSection'
import SecondSection from '@/components/SecondSection'
import ThirdSection from '@/components/ThirdSection'
import FourthSection from '@/components/FourthSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <FirstSection />
        <SecondSection />
        <ThirdSection />
      </Layout>
    </>
  )
}
